"""empty message

Revision ID: 7f7794134b87
Revises: 
Create Date: 2019-09-15 17:01:01.848500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7794134b87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'bank_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('branches_banks_fkey', 'branches', type_='foreignkey')
    op.create_foreign_key(None, 'branches', 'banks', ['bank_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_foreign_key('branches_banks_fkey', 'branches', 'banks', ['bank_id'], ['id'])
    op.alter_column('branches', 'bank_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
